apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversaotemperatura
spec:
  replicas: 3
  selector:
    matchLabels:
      app: conversaotemperatura
  template:
    metadata:
      labels:
        app: conversaotemperatura
    spec:
      containers:
      - name: conversaotemperatura
        image: gioufop/conversao-temperatura:v4
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: conversaotemperatura
spec:
  selector:
    app: conversaotemperatura
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 30000